version: '3.8'

services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile.source
    container_name: reader
    restart: always
    ports:
      - "4396:8080"
    volumes:
      - ./data/logs:/logs
      - ./data/storage:/storage
    mem_limit: 400m
    memswap_limit: 400m
    oom_kill_disable: false
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=50
      - READER_APP_USERBOOKLIMIT=200
      - READER_APP_CACHECHAPTERCONTENT=true
      - READER_APP_SECURE=true
      - READER_APP_SECUREKEY=adminpwd
      - READER_APP_INVITECODE=registercode
